<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $query = "INSERT INTO master_countries (id, name, country_code) VALUES
        ('1', 'Afghanistan', 'AF'),
        ('2', 'Albania', 'AL'),
        ('3', 'Algeria', 'DZ'),
        ('4', 'American Samoa', 'DS'),
        ('5', 'Andorra', 'AD'),
        ('6', 'Angola', 'AO'),
        ('7', 'Anguilla', 'AI'),
        ('8', 'Antarctica', 'AQ'),
        ('9', 'Antigua and Barbuda', 'AG'),
        ('10', 'Argentina', 'AR'),
        ('11', 'Armenia', 'AM'),
        ('12', 'Aruba', 'AW'),
        ('13', 'Australia', 'AU'),
        ('14', 'Austria', 'AT'),
        ('15', 'Azerbaijan', 'AZ'),
        ('16', 'Bahamas', 'BS'),
        ('17', 'Bahrain', 'BH'),
        ('18', 'Bangladesh', 'BD'),
        ('19', 'Barbados', 'BB'),
        ('20', 'Belarus', 'BY'),
        ('21', 'Belgium', 'BE'),
        ('22', 'Belize', 'BZ'),
        ('23', 'Benin', 'BJ'),
        ('24', 'Bermuda', 'BM'),
        ('25', 'Bhutan', 'BT'),
        ('26', 'Bolivia', 'BO'),
        ('27', 'Bosnia and Herzegovina', 'BA'),
        ('28', 'Botswana', 'BW'),
        ('29', 'Bouvet Island', 'BV'),
        ('30', 'Brazil', 'BR'),
        ('31', 'British Indian Ocean Territory', 'IO'),
        ('32', 'Brunei Darussalam', 'BN'),
        ('33', 'Bulgaria', 'BG'),
        ('34', 'Burkina Faso', 'BF'),
        ('35', 'Burundi', 'BI'),
        ('36', 'Cambodia', 'KH'),
        ('37', 'Cameroon', 'CM'),
        ('38', 'Canada', 'CA'),
        ('39', 'Cape Verde', 'CV'),
        ('40', 'Cayman Islands', 'KY'),
        ('41', 'Central African Republic', 'CF'),
        ('42', 'Chad', 'TD'),
        ('43', 'Chile', 'CL'),
        ('44', 'China', 'CN'),
        ('45', 'Christmas Island', 'CX'),
        ('46', 'Cocos (Keeling) Islands', 'CC'),
        ('47', 'Colombia', 'CO'),
        ('48', 'Comoros', 'KM'),
        ('49', 'Congo', 'CG'),
        ('50', 'Cook Islands', 'CK'),
        ('51', 'Costa Rica', 'CR'),
        ('52', 'Croatia (Hrvatska)', 'HR'),
        ('53', 'Cuba', 'CU'),
        ('54', 'Cyprus', 'CY'),
        ('55', 'Czech Republic', 'CZ'),
        ('56', 'Denmark', 'DK'),
        ('57', 'Djibouti', 'DJ'),
        ('58', 'Dominica', 'DM'),
        ('59', 'Dominican Republic', 'DO'),
        ('60', 'East Timor', 'TP'),
        ('61', 'Ecuador', 'EC'),
        ('62', 'Egypt', 'EG'),
        ('63', 'El Salvador', 'SV'),
        ('64', 'Equatorial Guinea', 'GQ'),
        ('65', 'Eritrea', 'ER'),
        ('66', 'Estonia', 'EE'),
        ('67', 'Ethiopia', 'ET'),
        ('68', 'Falkland Islands (Malvinas)', 'FK'),
        ('69', 'Faroe Islands', 'FO'),
        ('70', 'Fiji', 'FJ'),
        ('71', 'Finland', 'FI'),
        ('72', 'France', 'FR'),
        ('73', 'French Guiana', 'GF'),
        ('74', 'French Polynesia', 'PF'),
        ('75', 'French Southern Territories', 'TF'),
        ('76', 'Gabon', 'GA'),
        ('77', 'Gambia', 'GM'),
        ('78', 'Georgia', 'GE'),
        ('79', 'Germany', 'DE'),
        ('80', 'Ghana', 'GH'),
        ('81', 'Gibraltar', 'GI'),
        ('82', 'Guernsey', 'GK'),
        ('83', 'Greece', 'GR'),
        ('84', 'Greenland', 'GL'),
        ('85', 'Grenada', 'GD'),
        ('86', 'Guadeloupe', 'GP'),
        ('87', 'Guam', 'GU'),
        ('88', 'Guatemala', 'GT'),
        ('89', 'Guinea', 'GN'),
        ('90', 'Guinea-Bissau', 'GW'),
        ('91', 'Guyana', 'GY'),
        ('92', 'Haiti', 'HT'),
        ('93', 'Heard and Mc Donald Islands', 'HM'),
        ('94', 'Honduras', 'HN'),
        ('95', 'Hong Kong', 'HK'),
        ('96', 'Hungary', 'HU'),
        ('97', 'Iceland', 'IS'),
        ('98', 'India', 'IN'),
        ('99', 'Isle of Man', 'IM'),
        ('100', 'Indonesia', 'ID'),
        ('101', 'Iran', 'IR'),
        ('102', 'Iraq', 'IQ'),
        ('103', 'Ireland', 'IE'),
        ('104', 'Israel', 'IL'),
        ('105', 'Italy', 'IT'),
        ('106', 'Ivory Coast', 'CI'),
        ('107', 'Jersey', 'JE'),
        ('108', 'Jamaica', 'JM'),
        ('109', 'Japan', 'JP'),
        ('110', 'Jordan', 'JO'),
        ('111', 'Kazakhstan', 'KZ'),
        ('112', 'Kenya', 'KE'),
        ('113', 'Kiribati', 'KI'),
        ('114', 'Korea', 'KP'),
        ('115', 'Korea', 'KR'),
        ('116', 'Kosovo', 'XK'),
        ('117', 'Kuwait', 'KW'),
        ('118', 'Kyrgyzstan', 'KG'),
        ('119', 'Lao People', 'LA'),
        ('120', 'Latvia', 'LV'),
        ('121', 'Lebanon', 'LB'),
        ('122', 'Lesotho', 'LS'),
        ('123', 'Liberia', 'LR'),
        ('124', 'Libyan Arab Jamahiriya', 'LY'),
        ('125', 'Liechtenstein', 'LI'),
        ('126', 'Lithuania', 'LT'),
        ('127', 'Luxembourg', 'LU'),
        ('128', 'Macau', 'MO'),
        ('129', 'Macedonia', 'MK'),
        ('130', 'Madagascar', 'MG'),
        ('131', 'Malawi', 'MW'),
        ('132', 'Malaysia', 'MY'),
        ('133', 'Maldives', 'MV'),
        ('134', 'Mali', 'ML'),
        ('135', 'Malta', 'MT'),
        ('136', 'Marshall Islands', 'MH'),
        ('137', 'Martinique', 'MQ'),
        ('138', 'Mauritania', 'MR'),
        ('139', 'Mauritius', 'MU'),
        ('140', 'Mayotte', 'TY'),
        ('141', 'Mexico', 'MX'),
        ('142', 'Micronesia', 'FM'),
        ('143', 'Moldova', 'MD'),
        ('144', 'Monaco', 'MC'),
        ('145', 'Mongolia', 'MN'),
        ('146', 'Montenegro', 'ME'),
        ('147', 'Montserrat', 'MS'),
        ('148', 'Morocco', 'MA'),
        ('149', 'Mozambique', 'MZ'),
        ('150', 'Myanmar', 'MM'),
        ('151', 'Namibia', 'NA'),
        ('152', 'Nauru', 'NR'),
        ('153', 'Nepal', 'NP'),
        ('154', 'Netherlands', 'NL'),
        ('155', 'Netherlands Antilles', 'AN'),
        ('156', 'New Caledonia', 'NC'),
        ('157', 'New Zealand', 'NZ'),
        ('158', 'Nicaragua', 'NI'),
        ('159', 'Niger', 'NE'),
        ('160', 'Nigeria', 'NG'),
        ('161', 'Niue', 'NU'),
        ('162', 'Norfolk Island', 'NF'),
        ('163', 'Northern Mariana Islands', 'MP'),
        ('164', 'Norway', 'NO'),
        ('165', 'Oman', 'OM'),
        ('166', 'Pakistan', 'PK'),
        ('167', 'Palau', 'PW'),
        ('168', 'Palestine', 'PS'),
        ('169', 'Panama', 'PA'),
        ('170', 'Papua New Guinea', 'PG'),
        ('171', 'Paraguay', 'PY'),
        ('172', 'Peru', 'PE'),
        ('173', 'Philippines', 'PH'),
        ('174', 'Pitcairn', 'PN'),
        ('175', 'Poland', 'PL'),
        ('176', 'Portugal', 'PT'),
        ('177', 'Puerto Rico', 'PR'),
        ('178', 'Qatar', 'QA'),
        ('179', 'Reunion', 'RE'),
        ('180', 'Romania', 'RO'),
        ('181', 'Russian Federation', 'RU'),
        ('182', 'Rwanda', 'RW'),
        ('183', 'Saint Kitts and Nevis', 'KN'),
        ('184', 'Saint Lucia', 'LC'),
        ('185', 'Saint Vincent and the Grenadines', 'VC'),
        ('186', 'Samoa', 'WS'),
        ('187', 'San Marino', 'SM'),
        ('188', 'Sao Tome and Principe', 'ST'),
        ('189', 'Saudi Arabia', 'SA'),
        ('190', 'Senegal', 'SN'),
        ('191', 'Serbia', 'RS'),
        ('192', 'Seychelles', 'SC'),
        ('193', 'Sierra Leone', 'SL'),
        ('194', 'Singapore', 'SG'),
        ('195', 'Slovakia', 'SK'),
        ('196', 'Slovenia', 'SI'),
        ('197', 'Solomon Islands', 'SB'),
        ('198', 'Somalia', 'SO'),
        ('199', 'South Africa', 'ZA'),
        ('200', 'South Georgia South Sandwich Islands', 'GS'),
        ('201', 'Spain', 'ES'),
        ('202', 'Sri Lanka', 'LK'),
        ('203', 'St. Helena', 'SH'),
        ('204', 'St. Pierre and Miquelon', 'PM'),
        ('205', 'Sudan', 'SD'),
        ('206', 'Suriname', 'SR'),
        ('207', 'Svalbard and Jan Mayen Islands', 'SJ'),
        ('208', 'Swaziland', 'SZ'),
        ('209', 'Sweden', 'SE'),
        ('210', 'Switzerland', 'CH'),
        ('211', 'Syrian Arab Republic', 'SY'),
        ('212', 'Taiwan', 'TW'),
        ('213', 'Tajikistan', 'TJ'),
        ('214', 'Tanzania', 'TZ'),
        ('215', 'Thailand', 'TH'),
        ('216', 'Togo', 'TG'),
        ('217', 'Tokelau', 'TK'),
        ('218', 'Tonga', 'TO'),
        ('219', 'Trinidad and Tobago', 'TT'),
        ('220', 'Tunisia', 'TN'),
        ('221', 'Turkey', 'TR'),
        ('222', 'Turkmenistan', 'TM'),
        ('223', 'Turks and Caicos Islands', 'TC'),
        ('224', 'Tuvalu', 'TV'),
        ('225', 'Uganda', 'UG'),
        ('226', 'Ukraine', 'UA'),
        ('227', 'United Arab Emirates', 'AE'),
        ('228', 'United Kingdom', 'GB'),
        ('229', 'United States', 'US'),
        ('230', 'Uruguay', 'UY'),
        ('231', 'Uzbekistan', 'UZ'),
        ('232', 'Vanuatu', 'VU'),
        ('233', 'Vatican City State', 'VA'),
        ('234', 'Venezuela', 'VE'),
        ('235', 'Vietnam', 'VN'),
        ('236', 'Virgin Islands (British)', 'VG'),
        ('237', 'Virgin Islands (U.S.)', 'VI'),
        ('238', 'Wallis and Futuna Islands', 'WF'),
        ('239', 'Western Sahara', 'EH'),
        ('240', 'Yemen', 'YE'),
        ('241', 'Zaire', 'ZR'),
        ('242', 'Zambia', 'ZM'),
        ('243', 'Zimbabwe', 'ZW')";

        DB::unprepared($query);
    }
}
