<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterSkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $query = "INSERT INTO master_skills (Id, Name) VALUES
    ('1', 'Accountants'),
	('2', 'Accounts Clerk'),
	('3', 'Action Director'),
	('4', 'Action Director Assistant'),
	('5', 'Actor - Female '),
	('6', 'Actor - Male '),
	('7', 'Additional Casting'),
	('8', 'Additional Editor'),
	('9', 'Additional Second Assistant Director'),
	('10', 'ADR Mixer'),
	('11', 'ADR Voice Casting'),
	('12', 'Aerial Coordinator'),
	('13', 'Aerial Flight Director'),
	('14', 'Angel Investor '),
	('15', 'Animal Wrangler'),
	('16', 'Animation Director'),
	('17', 'Animation Supervisor'),
	('18', 'Animator '),
	('19', 'Arm Operators'),
	('20', 'Armourers'),
	('21', 'Armoury Security'),
	('22', 'Art Artists'),
	('23', 'Art Assistant'),
	('24', 'Art Associates '),
	('25', 'Art Dept. Coordinator'),
	('26', 'Art Director '),
	('27', 'Art PAs'),
	('28', 'Art Runner'),
	('29', 'Artificial Intelligence '),
	('30', 'Assistant Animator'),
	('31', 'Assistant Armourers'),
	('32', 'Assistant Art Director'),
	('33', 'Assistant Chef '),
	('34', 'Assistant Costume Designer'),
	('35', 'Assistant Director '),
	('36', 'Assistant Editor'),
	('37', 'Assistant Hair Stylist'),
	('38', 'Assistant Location Manager'),
	('39', 'Assistant Makeup Artist'),
	('40', 'Assistant Producer '),
	('41', 'Assistant Production Manager'),
	('42', 'Assistant Property Master'),
	('43', 'Assistant Script Editor'),
	('44', 'Assistant Script Supervisor'),
	('45', 'Assistant Set Decorator'),
	('46', 'Assistant Stunt Coordinator'),
	('47', 'Associate Director'),
	('48', 'Associate Editor'),
	('49', 'Associate Producer'),
	('50', 'Associate Set Decorator'),
	('51', 'Associate Set Designer'),
	('52', 'Auditor'),
	('53', 'Author'),
	('54', 'Background Artist'),
	('55', 'Background Designer'),
	('56', 'Best Boy'),
	('57', 'Best Boy Electric '),
	('58', 'Best Boy Rigging Electric'),
	('59', 'Boom Operator '),
	('60', 'Breakdown Artist'),
	('61', 'Breakdown Artist Key'),
	('62', 'Budgeting '),
	('63', 'Buyer Film Rights '),
	('64', 'Camera Assistant '),
	('65', 'Camera Attendants'),
	('66', 'Camera Dolly Grip'),
	('67', 'Camera Operator'),
	('68', 'Camera PA '),
	('69', 'Camera Trainee'),
	('70', 'Car Hunter /Mechanics'),
	('71', 'Caravan Suppliers'),
	('72', 'Carpenter'),
	('73', 'Cashier '),
	('74', 'Cast Driver'),
	('75', 'Casting Agent '),
	('76', 'Casting Assistant '),
	('77', 'Casting Associate'),
	('78', 'Casting Coordinator'),
	('79', 'Casting Director '),
	('80', 'Casting Producer'),
	('81', 'Caterer'),
	('82', 'Catering Manager '),
	('83', 'Character Designer'),
	('84', 'Chartered Accountant / CA'),
	('85', 'Chef'),
	('86', 'Choreographer '),
	('87', 'Choreographer Assistant/Associate  '),
	('88', 'Cinema Owner '),
	('89', 'Cinematographer'),
	('90', 'Clapper Loader'),
	('91', 'Cleaner/Launder'),
	('92', 'Co-Executive Producer'),
	('93', 'Co-Producer'),
	('94', 'Color Assistants'),
	('95', 'Colorist'),
	('96', 'Company Electrician '),
	('97', 'Compositing Supervisor'),
	('98', 'Compositor'),
	('99', 'Concept Artists'),
	('100', 'Construction Coordinator '),
	('101', 'Consultant '),
	('102', 'Continuity Supervisor '),
	('103', 'Costume Assistant'),
	('104', 'Costume Coordinator'),
	('105', 'Costume Designer '),
	('106', 'Costume Designer Assistant '),
	('107', 'Costume Supervisor'),
	('108', 'Costume Supervisor Assistant '),
	('109', 'Costume Tailor'),
	('110', 'Costumer'),
	('111', 'COVID Health & Safety Team'),
	('112', 'Craft Assistant '),
	('113', 'Craft Service Production Key'),
	('114', 'Crane Grip'),
	('115', 'Crane Grip Boy'),
	('116', 'Creative Director'),
	('117', 'Crowd Hair & Makeup Artist '),
	('118', 'Crowd Handler'),
	('119', 'Crowd Trainee'),
	('120', 'Dailies Colorist'),
	('121', 'Dancers'),
	('122', 'Data Entry/Wrangler'),
	('123', 'Data I/O'),
	('124', 'Dialect Coach'),
	('125', 'Dialogue Editor'),
	('126', 'Digital Artist'),
	('127', 'Digital Composer'),
	('128', 'Digital Composting Supervisor'),
	('129', 'Digital Intermediate Producer'),
	('130', 'Digital Loader'),
	('131', 'Digital Producer'),
	('132', 'Digital Recordist '),
	('133', 'Dimmer Board Operator'),
	('134', 'Director '),
	('135', 'Director of Photography (DoP)'),
	('136', 'Director\'s Assistant '),
	('137', 'Distributor '),
	('138', 'DIT'),
	('139', 'DIT Assistant'),
	('140', 'DMX Board Operator'),
	('141', 'Dolly Grip '),
	('142', 'Dressmen'),
	('143', 'Driver'),
	('144', 'Drone Assistant'),
	('145', 'Drone Camera Operator'),
	('146', 'Drone Pilot'),
	('147', 'Dubbing Artist '),
	('148', 'Dubbing Engineer'),
	('149', 'Dubbing Studio'),
	('150', 'Editor '),
	('151', 'Electrician '),
	('152', 'EPK Cameraman'),
	('153', 'Equity Investor '),
	('154', 'Event Management'),
	('155', 'Executive In-Charge of Production'),
	('156', 'Executive Producer '),
	('157', 'Exhibitor '),
	('158', 'Extra/Featured Casting Coordinator'),
	('159', 'Extras Casting Assistant'),
	('160', 'F&B Suppliers '),
	('161', 'Festival Programmer '),
	('162', 'Fight Coordinator'),
	('163', 'Film Commission '),
	('164', 'Film Critic'),
	('165', 'Film Fund'),
	('166', 'Film Loader'),
	('167', 'Film Rights '),
	('168', 'Filmmaker - Documentary '),
	('169', 'Filmmaker - Feature '),
	('170', 'Filmmaker - Series '),
	('171', 'Filmmaker - Short'),
	('172', 'Financial Controller - Key'),
	('173', 'Finishing Editor'),
	('174', 'First Assistant Camera (1st AC)'),
	('175', 'First Assistant Director (1st AD)'),
	('176', 'Floor Manager'),
	('177', 'Focus Puller'),
	('178', 'Foley Artist '),
	('179', 'Foley Mixer/Editor/Recordist'),
	('180', 'Food stylist'),
	('181', 'Franchise Supplier'),
	('182', 'Gaffer'),
	('183', 'Gaming Content Creator'),
	('184', 'Generator Operator '),
	('185', 'Generator Supplier'),
	('186', 'Gimbal Operator'),
	('187', 'Graphics Designer '),
	('188', 'Green Supervisor'),
	('189', 'Greensmen'),
	('190', 'Grim Support Electrician'),
	('191', 'Grips'),
	('192', 'Grip Best Boy'),
	('193', 'Grip Department Translator'),
	('194', 'Hair Department Head'),
	('195', 'Hair Stylist'),
	('196', 'Hair Stylist Assistant/Trainee'),
	('197', 'Head of Production'),
	('198', 'Hotels'),
	('199', 'Housekeeping (on-set)'),
	('200', 'Illustrator '),
	('201', 'Image Scientist'),
	('202', 'Inbetween Artist'),
	('203', 'Insurance Provider'),
	('204', 'Intern'),
	('205', 'Intimacy Choreographer '),
	('206', 'Intimacy Coordinator '),
	('207', 'Intimacy Director '),
	('208', 'Journalist'),
	('209', 'Junior Artist Provider'),
	('210', 'Junior Writer'),
	('211', 'Key Animator'),
	('212', 'Key Assistant Location Manager'),
	('213', 'Key Costumer'),
	('214', 'Key Craft Services '),
	('215', 'Key Grip'),
	('216', 'Key Hair Stylist'),
	('217', 'Key Makeup Artist'),
	('218', 'Key PA'),
	('219', 'Key Scenic'),
	('220', 'Key Set Medics'),
	('221', 'Key Stunt Rigger'),
	('222', 'Labour Coordinator '),
	('223', 'Labour Supervisor '),
	('224', 'Laundry Services'),
	('225', 'Layout Artist'),
	('226', 'Leadman '),
	('227', 'Legal Counsel '),
	('228', 'Librarian'),
	('229', 'Light Boys'),
	('230', 'Light Equipment '),
	('231', 'Lighting Technician'),
	('232', 'Line Producer'),
	('233', 'Loader '),
	('234', 'Location Assistant '),
	('235', 'Location Coordinator'),
	('236', 'Location Director'),
	('237', 'Location Manager '),
	('238', 'Location Production Assistant'),
	('239', 'Location Sound Recordist '),
	('240', 'Makeup Artist'),
	('241', 'Makeup Assistant '),
	('242', 'Makeup Department Head'),
	('243', 'Makeup Desinger'),
	('244', 'Makeup Trainee'),
	('245', 'Marine Coordinator'),
	('246', 'Marine Technicians'),
	('247', 'Media Management '),
	('248', 'Mentors'),
	('249', 'Merchandise '),
	('250', 'Mixing Studio'),
	('251', 'Model Maker'),
	('252', 'Moulder'),
	('253', 'Music Composer '),
	('254', 'Music Director'),
	('255', 'Music Editor'),
	('256', 'Music Producer'),
	('257', 'Music Supervisor'),
	('258', 'Musician'),
	('259', 'Office PAs '),
	('260', 'On-line Editor'),
	('261', 'On-set Dresser'),
	('262', 'On-set Vehicles Art Director'),
	('263', 'On-set Assistant Editor'),
	('264', 'On-set Auditors '),
	('265', 'On-set Carpenter '),
	('266', 'Orchestra Conductor '),
	('267', 'Painter'),
	('268', 'Permits Manager (Location)'),
	('269', 'Personal Assistants '),
	('270', 'Picture Vehicle Coordinator'),
	('271', 'Plasterer Head '),
	('272', 'Playback Singer'),
	('273', 'Post Producer'),
	('274', 'Post Production Accountant'),
	('275', 'Post Production Coordinator '),
	('276', 'Post Production Services (Vendor)'),
	('277', 'Post Production Supervisor'),
	('278', 'Post-Production Assistant'),
	('279', 'Post-Production Manager'),
	('280', 'Producer'),
	('281', 'Producer\'s Assistant'),
	('282', 'Production Accountant'),
	('283', 'Production Assistant '),
	('284', 'Production Boys (Spot Boys)'),
	('285', 'Production Coordinator '),
	('286', 'Production Design Assistant '),
	('287', 'Production Designer'),
	('288', 'Production Driver'),
	('289', 'Production Equipment Supplier'),
	('290', 'Production Legal Services'),
	('291', 'Production Manager '),
	('292', 'Production Secretary '),
	('293', 'Production Staff'),
	('294', 'Production Supervisor '),
	('295', 'Projectionist '),
	('296', 'Prop Maker'),
	('297', 'Property Master'),
	('298', 'Props'),
	('299', 'Props Assistant'),
	('300', 'Prosthetics Advanced '),
	('301', 'Prosthetics Artist'),
	('302', 'Prosthetics Basic '),
	('303', 'Publicist '),
	('304', 'Publisher'),
	('305', 'Pyrotechnic Effects'),
	('306', 'Railway Coordinator '),
	('307', 'Re-Recording Mixer'),
	('308', 'Recording Assistant'),
	('309', 'Remote Head Technician'),
	('310', 'Researcher'),
	('311', 'Rigging Gaffers'),
	('312', 'Rigging Grips'),
	('313', 'Sales Agent'),
	('314', 'Scenic Artist '),
	('315', 'Scheduler '),
	('316', 'Score Editor'),
	('317', 'Scoring Stage Manager'),
	('318', 'Script Assistant'),
	('319', 'Script Consultant'),
	('320', 'Script Coordinator'),
	('321', 'Script Doctor '),
	('322', 'Script Editor'),
	('323', 'Script Supervisor '),
	('324', 'Sculptor '),
	('325', 'Seamstress '),
	('326', 'Second Assistant Camera (2nd AC)'),
	('327', 'Second Assistant Director (2nd AD)'),
	('328', 'Second Director'),
	('329', 'Second Second Assistant Director (2nd 2nd AD)'),
	('330', 'Second Unit Director'),
	('331', 'Segment Producer'),
	('332', 'Series Producer'),
	('333', 'Service Driver'),
	('334', 'Set Buyers'),
	('335', 'Set Carpenter'),
	('336', 'Set Costumer'),
	('337', 'Set Decorator '),
	('338', 'Set Designer'),
	('339', 'Set Dresser '),
	('340', 'Set PA '),
	('341', 'Set Runner'),
	('342', 'Set Scenic Artist'),
	('343', 'Setting Boys'),
	('344', 'SFX Editor (Sound)'),
	('345', 'SFX Technician '),
	('346', 'Shipping and Transport'),
	('347', 'Shooting Floors'),
	('348', 'Shopper'),
	('349', 'Shotover DOP'),
	('350', 'Showrunner'),
	('351', 'Sign Board Artist'),
	('352', 'Sign Writer'),
	('353', 'Singer'),
	('354', 'Sound Cableman'),
	('355', 'Sound Design Studios'),
	('356', 'Sound Designer'),
	('357', 'Sound Editor'),
	('358', 'Sound Effects Editor'),
	('359', 'Sound Mixer'),
	('360', 'Sound Producer'),
	('361', 'Sound Recordist'),
	('362', 'Sound Supervisor '),
	('363', 'Sound Utility '),
	('364', 'Special Effects'),
	('365', 'Special Effects Assistant'),
	('366', 'Special Effects Coordinator '),
	('367', 'Special Effects Crew'),
	('368', 'Special Effects Foreman '),
	('369', 'Special Effects Makeup'),
	('370', 'Special Effects Supervisor '),
	('371', 'Special Effects Technician'),
	('372', 'Special Makeup Effects Artist'),
	('373', 'Stage Manager'),
	('374', 'Stand-by Props'),
	('375', 'Steadicam Operator '),
	('376', 'Still Photographer '),
	('377', 'Storeman '),
	('378', 'Storyboard Artist'),
	('379', 'Stunt Actor'),
	('380', 'Stunt Administrator'),
	('381', 'Stunt Coordinator'),
	('382', 'Stunt Coordinator Assistant'),
	('383', 'Stunt Costumer'),
	('384', 'Stunt Double'),
	('385', 'Stunt Driver'),
	('386', 'Stunt Equipment Assistant'),
	('387', 'Stunt Office Coordinator'),
	('388', 'Stunt Performer '),
	('389', 'Stunt Rigger'),
	('390', 'Stunts'),
	('391', 'Stylist'),
	('392', 'Subtitlist/Subtitles '),
	('393', 'Supervising Art Director'),
	('394', 'Supervising Editor'),
	('395', 'Supervising Location Manager'),
	('396', 'Supervising Producer'),
	('397', 'Sync Security'),
	('398', 'Tapist'),
	('399', 'Tattoo Artist'),
	('400', 'TBL Manager '),
	('401', 'Technical Advisor '),
	('402', 'Technical Director'),
	('403', 'Technologist'),
	('404', 'Theatre Manager '),
	('405', 'Theme Music Composer'),
	('406', 'Third Assistant Director (3rd AD)'),
	('407', 'Title Music'),
	('408', 'Titles Designer'),
	('409', 'Trailer Editor '),
	('410', 'Trainee Assistant Director'),
	('411', 'Tranportation Captain'),
	('412', 'Translators'),
	('413', 'Transport Suppliers '),
	('414', 'Transportation '),
	('415', 'Transportation Co-Captain'),
	('416', 'Transportation Coordinator'),
	('417', 'Travel Agent '),
	('418', 'Travel Consultants'),
	('419', 'Travel Coordinators'),
	('420', 'Underwater DP'),
	('421', 'Underwater Focus Puller'),
	('422', 'Unit Driver'),
	('423', 'Unit Manager'),
	('424', 'Unit PA '),
	('425', 'Unit Production Manager '),
	('426', 'Unit Publicist '),
	('427', 'Utility Stunts'),
	('428', 'Vanity Van Suppliers'),
	('429', 'Venture Capital Fund '),
	('430', 'VFX Producer'),
	('431', 'VFX Studios'),
	('432', 'VFX Supervisor '),
	('433', 'Video Playback'),
	('434', 'Video Playback Assistants'),
	('435', 'Vision Mixer'),
	('436', 'Visual Effects '),
	('437', 'Visual Effects Artist'),
	('438', 'Visual Effects Coordinator'),
	('439', 'Visual Effects Editor'),
	('440', 'Visual Effects Prodcuer'),
	('441', 'Visual Effects Supervisor'),
	('442', 'Voice-over '),
	('443', 'Walkie Supplier'),
	('444', 'Wardrobe'),
	('445', 'Wardrobe Assistant'),
	('446', 'Wardrobe Supervisor '),
	('447', 'Weapons Maker'),
	('448', 'Weapons Master'),
	('449', 'Welder - Head '),
	('450', 'Wig Makers'),
	('451', 'Workshop Assistant'),
	('452', 'Workshop Director'),
	('453', 'Workshop Director Assistant'),
	('454', 'Writer'),
	('455', 'Writer - Adapted Screenplay '),
	('456', 'Writer - Commissioned '),
	('457', 'Writer - Dialogue '),
	('458', 'Writer - Feature '),
	('459', 'Writer - Series '),
	('460', 'Writer - Sub-Titles '),
	('461', 'Writer - Video Games '),
	('462', 'Writers\' Room '),
	('463', 'Other')";
       

    DB::unprepared($query);
    }
}
