<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterSkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $query = "INSERT INTO master_skills (Id, Name) VALUES
        ('1', 'Camera Assistant'),
        ('2', 'Camera Assistant 1st'),
        ('3', 'Camera Assistant 2nd'),
        ('4', 'Camera Attendants'),
        ('5', 'Camera Department Translator'),
        ('6', 'Camera Dolly Grip'),
        ('7', 'Camera Intern/ 3rd AC'),
        ('8', 'Camera PA'),
        ('9', 'Camera Trainee'),
        ('10', 'Car Hunter /Mechanics'),
        ('11', 'Caravan Suppliers'),
        ('12', 'Carpenters'),
        ('13', 'Cashier'),
        ('14', 'Casting Agent'),
        ('15', 'Casting Assistant'),
        ('16', 'Casting Director'),
        ('17', 'Caterer'),
        ('18', 'Catering Manager'),
        ('19', 'Chartered Accountant / CA'),
        ('20', 'Chef'),
        ('21', 'Choreographer'),
        ('22', 'Choreographer Assistant/Associate'),
        ('23', 'Cinema Owner'),
        ('24', 'Clapper Loader'),
        ('25', 'Cleaner/Launder'),
        ('26', 'Color Assistants'),
        ('27', 'Colorist'),
        ('28', 'Company Electrician'),
        ('29', 'Concept Artists'),
        ('30', 'Construction Coordinator'),
        ('31', 'Consultant'),
        ('32', 'Continuity Supervisor'),
        ('33', 'Costume Coordinator'),
        ('34', 'Costume Designer'),
        ('35', 'Costume Designer Assistant'),
        ('36', 'Costume Main Cutter'),
        ('37', 'Costume Supervisor'),
        ('38', 'Costume Supervisor Assistant'),
        ('39', 'Costume Tailor'),
        ('40', 'COVID Health & Safety Team'),
        ('41', 'Craft Assistant'),
        ('42', 'Craft Service Production Key'),
        ('43', 'Crane Grip'),
        ('44', 'Crane Grip Boy'),
        ('45', 'Crowd Hair & Makeup Artist'),
        ('46', 'Crowd Handler'),
        ('47', 'Crowd Trainee'),
        ('48', 'Best boy Electric'),
        ('49', 'Best Boy Rigging Electric'),
        ('50', 'Book Adaptations'),
        ('51', 'Boom Operator'),
        ('52', 'Breakdown Artist'),
        ('53', 'Breakdown Artist Key'),
        ('54', 'Budgeting'),
        ('55', 'Buyer Film Rights'),
        ('56', 'Accountants'),
        ('57', 'Accounts Clerk'),
        ('58', 'Action Director'),
        ('59', 'Action Director Assistant'),
        ('60', 'Actor - Female'),
        ('61', 'Actor - Male'),
        ('62', 'Adaptations'),
        ('63', 'Aerial Coordinator'),
        ('64', 'Aerial Flight Director'),
        ('65', 'Ambulance Nurses'),
        ('66', 'Ambulance Service'),
        ('67', 'Angel Investor'),
        ('68', 'Animal Wrangler'),
        ('69', 'Animator'),
        ('70', 'Arm Operators'),
        ('71', 'Armorer/Pyrotechnis'),
        ('72', 'Armourers'),
        ('73', 'Armoury Security'),
        ('74', 'Art Artists'),
        ('75', 'Art Assistant'),
        ('76', 'Art Associates'),
        ('77', 'Art Dept. Coordinator'),
        ('78', 'Art Director'),
        ('79', 'Art PAs'),
        ('80', 'Art Runner'),
        ('81', 'Artificial Intelligence'),
        ('82', 'Assistant Armourers'),
        ('83', 'Assistant Chef'),
        ('84', 'Assistant Director'),
        ('85', 'Assistant Producer'),
        ('86', 'Assistant Property Master'),
        ('87', 'Assistant Set Decorator'),
        ('88', 'Associate Director'),
        ('89', 'Associate Producer'),
        ('90', 'Associate Set Decorator'),
        ('91', 'Associate Set Designer'),
        ('92', 'Associate/Assistant Editor'),
        ('93', 'Auditor'),
        ('94', 'Authors'),
        ('95', 'Dailies Colorist'),
        ('96', 'Dancers'),
        ('97', 'Data Entry/Wrangler'),
        ('98', 'Data I/O'),
        ('99', 'Dialect Coach'),
        ('100', 'Dialogue Editor/ADR Mixer'),
        ('101', 'Digital Composting Supervisor'),
        ('102', 'Digital Intermediate Producer'),
        ('103', 'Digital Loader'),
        ('104', 'Digital Recordist'),
        ('105', 'Dimmer Board Operator'),
        ('106', 'Director'),
        ('107', 'Director of Photography (DoP)'),
        ('108', 'Director\'s Assistant'),
        ('109', 'Distributor'),
        ('110', 'DIT'),
        ('111', 'DIT Assistant'),
        ('112', 'DIT/ Media Management'),
        ('113', 'DMX Board Operator'),
        ('114', 'Dolly Grip'),
        ('115', 'Draughts person'),
        ('116', 'Dressmen'),
        ('117', 'Driver'),
        ('118', 'Drone Assistant'),
        ('119', 'Drone Camera Operator'),
        ('120', 'Drone Pilot'),
        ('121', 'Dubbing Artist'),
        ('122', 'Dubbing Engineer'),
        ('123', 'Duplicates'),
        ('124', 'Filmmaker - Documentary'),
        ('125', 'Filmmaker - Feature'),
        ('126', 'Filmmaker - Series'),
        ('127', 'Filmmaker - Short'),
        ('128', 'Financial Controller - Key'),
        ('129', 'Finishing Editor'),
        ('130', 'Floor Manager'),
        ('131', 'Focus Puller'),
        ('132', 'Foley Artist'),
        ('133', 'Foley Mixer/Editor/Recordist'),
        ('134', 'Food stylist'),
        ('135', 'Franchise Supplier'),
        ('136', 'Editor'),
        ('137', 'Electrician'),
        ('138', 'EPK Cameraman'),
        ('139', 'Event Management'),
        ('140', 'Equity Investor'),
        ('141', 'Executive Producer'),
        ('142', 'Exhibitor'),
        ('143', 'Extra/Featured Casting Coordinator'),
        ('144', 'F&B Suppliers'),
        ('145', 'Festival Programmer'),
        ('146', 'Fight Coordinator'),
        ('147', 'Film Commission'),
        ('148', 'Film Critic'),
        ('149', 'Film Fund'),
        ('150', 'Film Loader'),
        ('151', 'Gaffer'),
        ('152', 'Gaming Content Creator'),
        ('153', 'Generator Operator'),
        ('154', 'Generator Supplier'),
        ('155', 'Gimbal Operator'),
        ('156', 'Graphics Designer'),
        ('157', 'Green Supervisor'),
        ('158', 'Greensmen'),
        ('159', 'Grim Support Electrician'),
        ('160', 'Grip Best Boy'),
        ('161', 'Grip Department Translator'),
        ('162', 'Grip Key (Panther, Crane, Tracks)'),
        ('163', 'Illustrator'),
        ('164', 'Image Scientist'),
        ('165', 'Insurance Provider'),
        ('166', 'Intern'),
        ('167', 'Intimacy Choreographer'),
        ('168', 'Intimacy Coordinator'),
        ('169', 'Intimacy Director'),
        ('170', 'Housekeeping (on-set)'),
        ('171', 'Hair Deptt. Head'),
        ('172', 'Hair Stylist'),
        ('173', 'Hair Stylist Assistant/Trainee'),
        ('174', 'Journalist'),
        ('175', 'Junior Writer'),
        ('176', 'Key Craft Services'),
        ('177', 'Key Hair Department'),
        ('178', 'Key Makeup Department'),
        ('179', 'Key PA'),
        ('180', 'Key Scenic'),
        ('181', 'Key Set Medics'),
        ('182', 'Key Stunt Rigger'),
        ('183', 'Underwater DP'),
        ('184', 'Underwater Focus Puller'),
        ('185', 'Unit PA'),
        ('186', 'Unit Production Manager'),
        ('187', 'Unit Publicist'),
        ('188', 'Tapist'),
        ('189', 'Tattoo Artist'),
        ('190', 'TBL Manager'),
        ('191', 'Technical Advisor'),
        ('192', 'Technologist'),
        ('193', 'Theatre Manager'),
        ('194', 'Titles Designer'),
        ('195', 'Trailer Editor'),
        ('196', 'Tranportation Captain'),
        ('197', 'Translators'),
        ('198', 'Transport Suppliers'),
        ('199', 'Transportation Co-Captain'),
        ('200', 'Transportation Coordinator'),
        ('201', 'Travel Agent'),
        ('202', 'Travel Consultants'),
        ('203', 'Travel Coordinators'),
        ('204', 'Scenic Artist'),
        ('205', 'Scheduler'),
        ('206', 'Score Editor'),
        ('207', 'Scoring Stage Manager'),
        ('208', 'Script Doctor'),
        ('209', 'Script Supervisor'),
        ('210', 'Sculptor'),
        ('211', 'Seamstress'),
        ('212', 'Set Buyers'),
        ('213', 'Set Carpenter'),
        ('214', 'Set Costumes'),
        ('215', 'Set Decorator'),
        ('216', 'Set Designer'),
        ('217', 'Set Dresser'),
        ('218', 'Set PA'),
        ('219', 'Set Runner'),
        ('220', 'Set Scenic Artist'),
        ('221', 'Setting Boys'),
        ('222', 'SFX Editor (Sound)'),
        ('223', 'SFX Technician'),
        ('224', 'Shipping and Transport'),
        ('225', 'Shooting Floors'),
        ('226', 'Shopper'),
        ('227', 'Shotover DOP'),
        ('228', 'Showrunner'),
        ('229', 'Sigh Board Artist'),
        ('230', 'Sign Writer'),
        ('231', 'Sound Cableman'),
        ('232', 'Sound Design Studios'),
        ('233', 'Sound Editor'),
        ('234', 'Sound Mixer/ Designer'),
        ('235', 'Sound Producer'),
        ('236', 'Sound Supervisor'),
        ('237', 'Sound Utility'),
        ('238', 'Special Effects Coordinator'),
        ('239', 'Special Effects Foreman'),
        ('240', 'Special Effects Makeup/ Prosthetics Artist'),
        ('241', 'Special Effects Supervisor'),
        ('242', 'Stand-by Props'),
        ('243', 'Steadicam Operator'),
        ('244', 'Still Photographer'),
        ('245', 'Storeman'),
        ('246', 'Storyboard Artists'),
        ('247', 'Stunt Administrator'),
        ('248', 'Stunt Coordinator'),
        ('249', 'Stunt Coordinator Assistant'),
        ('250', 'Stunt Costumer'),
        ('251', 'Stunt Double'),
        ('252', 'Stunt Equipment Assistant'),
        ('253', 'Stunt Office Coordinator'),
        ('254', 'Stunt Performer'),
        ('255', 'Sub-titles'),
        ('256', 'Subtitlist/Subtitles'),
        ('257', 'Supervising Art Director'),
        ('258', 'Swing Gang'),
        ('259', 'Sync Security'),
        ('260', 'Railway Coordinator'),
        ('261', 'Re-recording Mixer'),
        ('262', 'Re-writing'),
        ('263', 'Recording Assistant'),
        ('264', 'Remake Rights'),
        ('265', 'Remote Head Technician'),
        ('266', 'Researcher'),
        ('267', 'Rigging Gaffers'),
        ('268', 'Rigging Grips'),
        ('269', 'Painter'),
        ('270', 'Permits Manager (Location)'),
        ('271', 'Personal Assistants'),
        ('272', 'Picture Vehicle Coordinator'),
        ('273', 'Plasterer Head'),
        ('274', 'Post Producer'),
        ('275', 'Post Production Accountant'),
        ('276', 'Post Production Assistants'),
        ('277', 'Post Production Coordinator'),
        ('278', 'Post Production Services (Vendor)'),
        ('279', 'Post Production Supervisor'),
        ('280', 'Producer'),
        ('281', 'Producer Assistant'),
        ('282', 'Production Accountants'),
        ('283', 'Production Assistant'),
        ('284', 'Production Boys (Spot Boys)'),
        ('285', 'Production Coordinator'),
        ('286', 'Production Design Assistant'),
        ('287', 'Production Designer'),
        ('288', 'Production Equipment Supplier'),
        ('289', 'Production Legal Services'),
        ('290', 'Production Manager'),
        ('291', 'Production Secretary'),
        ('292', 'Production Supervisor'),
        ('293', 'Projectionist'),
        ('294', 'Projectionist'),
        ('295', 'Prop Assistants'),
        ('296', 'Prop Maker'),
        ('297', 'Property Master'),
        ('298', 'Props Assistant'),
        ('299', 'Prosthetics Advanced'),
        ('300', 'Prosthetics Basic'),
        ('301', 'Publicist'),
        ('302', 'Publisher'),
        ('303', 'Publishers'),
        ('304', 'Office PAs'),
        ('305', 'On Set Dresser'),
        ('306', 'On Set Vehicles Art Director'),
        ('307', 'On-set Assistant Editor'),
        ('308', 'On-set Auditors'),
        ('309', 'On-set Carpenter'),
        ('310', 'Orchestra Conductor'),
        ('311', 'Makeup Assistant'),
        ('312', 'Makeup Deptt. Head'),
        ('313', 'Makeup Trainee'),
        ('314', 'Marine Coordinator'),
        ('315', 'Marine Technicians'),
        ('316', 'Mentors'),
        ('317', 'Merchandise'),
        ('318', 'Mixing Studio'),
        ('319', 'Model Maker'),
        ('320', 'Moulder'),
        ('321', 'Music Composer'),
        ('322', 'Music Director'),
        ('323', 'Labour Coordinator'),
        ('324', 'Labour Supervisor'),
        ('325', 'Laundry Services'),
        ('326', 'Leadman'),
        ('327', 'Legal Counsel'),
        ('328', 'Librarian'),
        ('329', 'Light Boys'),
        ('330', 'Light Equipment'),
        ('331', 'Line Producer'),
        ('332', 'Loader'),
        ('333', 'Location Assistant'),
        ('334', 'Location Manager'),
        ('335', 'Location Scout'),
        ('336', 'Location Sound Recordist'),
        ('337', 'Walkie Supplier'),
        ('338', 'Wardrobe Assistant'),
        ('339', 'Wardrobe Supervisor'),
        ('340', 'Weapons Maker'),
        ('341', 'Welder - Head'),
        ('342', 'Wig Makers'),
        ('343', 'Workshop Assistant'),
        ('344', 'Workshop Director'),
        ('345', 'Writer'),
        ('346', 'Writer - Adapted Screenplay'),
        ('347', 'Writer - Commissioned'),
        ('348', 'Writer - Dialogue'),
        ('349', 'Writer - Feature'),
        ('350', 'Writer - Series'),
        ('351', 'Writer - Sub-Titles'),
        ('352', 'Writer - Video Games'),
        ('353', 'Writers\' Room'),
        ('354', 'Vanity Van Suppliers'),
        ('355', 'Venture Capital Fund'),
        ('356', 'VFX Producer'),
        ('357', 'VFX Studios'),
        ('358', 'VFX Supervisor'),
        ('359', 'Video Playback'),
        ('360', 'Video Playback Assistants'),
        ('361', 'Visual Effects'),
        ('362', 'Voice-over')";

    DB::unprepared($query);
    }
}
