<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterLanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // INSERT INTO tableName (id, name) VALUES
    $query = "INSERT INTO `master_languages` (`id`, `name`) VALUES
	('1', 'English'),
	('2', 'Assamese'),
	('3', 'Bengali'),
	('4', 'Bodo'),
	('5', 'Dogri'),
	('6', 'Gujarati'),
	('7', 'Hindi'),
	('8', 'Kannada'),
	('9', 'Kashmiri'),
	('10', 'Konkani'),
	('11', 'Maithili'),
	('12', 'Malayalam'),
	('13', 'Manipuri'),
	('14', 'Marathi'),
	('15', 'Nepali'),
	('16', 'Oriya/ Odia'),
	('17', 'Punjabi/ Panjabi'),
	('18', 'Sanskrit'),
	('19', 'Santhali/ Santali'),
	('20', 'Sindhi'),
	('21', 'Tamil'),
	('22', 'Telugu'),
	('23', 'Urdu'),
	('24', 'Abkhazian'),
	('25', 'Afar'),
	('26', 'Afrikaans'),
	('27', 'Akan'),
	('28', 'Albanian'),
	('29', 'Amharic'),
	('30', 'Arabic'),
	('31', 'Aragonese'),
	('32', 'Armenian'),
	('33', 'Avaric'),
	('34', 'Avestan'),
	('35', 'Aymara'),
	('36', 'Azerbaijani'),
	('37', 'Bambara'),
	('38', 'Bashkir'),
	('39', 'Basque'),
	('40', 'Belarusian'),
	('41', 'Bislama'),
	('42', 'Bosnian'),
	('43', 'Breton'),
	('44', 'Bulgarian'),
	('45', 'Burmese'),
	('46', 'Catalan, Valencian'),
	('47', 'Chamorro'),
	('48', 'Chechen'),
	('49', 'Chichewa, Chewa, Nyanja'),
	('50', 'Chinese'),
	('51', 'Church Slavonic, Old Slavonic, Old Church Slavonic'),
	('52', 'Chuvash'),
	('53', 'Cornish'),
	('54', 'Corsican'),
	('55', 'Cree'),
	('56', 'Croatian'),
	('57', 'Czech'),
	('58', 'Danish'),
	('59', 'Divehi, Dhivehi, Maldivian'),
	('60', 'Dutch, Flemish'),
	('61', 'Dzongkha'),
	('62', 'Esperanto'),
	('63', 'Estonian'),
	('64', 'Ewe'),
	('65', 'Faroese'),
	('66', 'Fijian'),
	('67', 'Filipino'),
	('68', 'Finnish'),
	('69', 'French'),
	('70', 'Western Frisian'),
	('71', 'Fulah'),
	('72', 'Gaelic, Scottish Gaelic'),
	('73', 'Galician'),
	('74', 'Ganda'),
	('75', 'Georgian'),
	('76', 'German'),
	('77', 'Greek'),
	('78', 'Kalaallisut, Greenlandic'),
	('79', 'Guarani'),
	('80', 'Haitian, Haitian Creole'),
	('81', 'Hausa'),
	('82', 'Hebrew'),
	('83', 'Herero'),
	('84', 'Hiri Motu'),
	('85', 'Hungarian'),
	('86', 'Icelandic'),
	('87', 'Ido'),
	('88', 'Igbo'),
	('89', 'Indonesian'),
	('90', 'Interlingua (International Auxiliary Language Association)'),
	('91', 'Interlingue, Occidental'),
	('92', 'Inuktitut'),
	('93', 'Inupiaq'),
	('94', 'Irish'),
	('95', 'Italian'),
	('96', 'Japanese'),
	('97', 'Javanese'),
	('98', 'Kanuri'),
	('99', 'Kazakh'),
	('100', 'Khmer'),
	('101', 'Kikuyu, Gikuyu'),
	('102', 'Kinyarwanda'),
	('103', 'Kirghiz, Kyrgyz'),
	('104', 'Komi'),
	('105', 'Kongo'),
	('106', 'Korean'),
	('107', 'Kuanyama, Kwanyama'),
	('108', 'Kurdish'),
	('109', 'Lao'),
	('110', 'Latin'),
	('111', 'Latvian'),
	('112', 'Limburgan, Limburger, Limburgish'),
	('113', 'Lingala'),
	('114', 'Lithuanian'),
	('115', 'Luba-Katanga'),
	('116', 'Luxembourgish, Letzwburgesch'),
	('117', 'Macdonian'),
	('118', 'Malagasy'),
	('119', 'Malay'),
	('120', 'Maltese'),
	('121', 'Manx'),
	('122', 'Maori'),
	('123', 'Marshallese'),
	('124', 'Mongolian'),
	('125', 'Nauru'),
	('126', 'Navajo, Navaho'),
	('127', 'Ndebele (North)'),
	('128', 'Ndebele (South)'),
	('129', 'Ndonga'),
	('130', 'Norwegian'),
	('131', 'Norwegian Bokmål'),
	('132', 'Norwegian Nynorsk'),
	('133', 'Sichuan Yi, Nuosu'),
	('134', 'Occitan'),
	('135', 'Ojibwa'),
	('136', 'Oromo'),
	('137', 'Ossetian, Ossetic'),
	('138', 'Pali'),
	('139', 'Pashto, Pushto'),
	('140', 'Persian'),
	('141', 'Polish'),
	('142', 'Portuguese'),
	('143', 'Quechua'),
	('144', 'Romanian, Moldovian, Moldovan'),
	('145', 'Romansh'),
	('146', 'Rundi'),
	('147', 'Russian'),
	('148', 'Sami (Northern)'),
	('149', 'Samoan'),
	('150', 'Sango'),
	('151', 'Sanskrit'),
	('152', 'Sardinian'),
	('153', 'Serbian'),
	('154', 'Shona'),
	('155', 'Sinhala, Sinhalese'),
	('156', 'Slovak'),
	('157', 'Slovenian'),
	('158', 'Somali'),
	('159', 'Southern Sotho'),
	('160', 'Spanish, Castilian'),
	('161', 'Sundanese'),
	('162', 'Swahili'),
	('163', 'Swati'),
	('164', 'Swedish'),
	('165', 'Tagalog'),
	('166', 'Tahitian'),
	('167', 'Tajik'),
	('168', 'Tatar'),
	('169', 'Thai'),
	('170', 'Tibetan'),
	('171', 'Tigrinya'),
	('172', 'Tonga'),
	('173', 'Tsonga'),
	('174', 'Tswana'),
	('175', 'Turkish'),
	('176', 'Turkmen'),
	('177', 'Twi'),
	('178', 'Uighur, Uyghur'),
	('179', 'Ukranian'),
	('180', 'Uzbek'),
	('181', 'Venda'),
	('182', 'Vietnamese'),
	('183', 'Volapük'),
	('184', 'Walloon'),
	('185', 'Welsh'),
	('186', 'Wolof'),
	('187', 'Xhosa'),
	('188', 'Yiddish'),
	('189', 'Yoruba'),
	('190', 'Zhuang, Chuang'),
	('191', 'Zulu')";
    DB::unprepared($query);
    }
}
